-- =============================================================================
-- LOTO IMPERIAL - FULL DATABASE SCHEMA & DATA SEED
-- =============================================================================

-- 1. TABLES SETUP
-- =============================================================================

-- Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'cliente' CHECK (role IN ('cliente', 'admin')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Menu Categories Table
CREATE TABLE IF NOT EXISTS menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Menu Items Table
CREATE TABLE IF NOT EXISTS menu_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  category_id BIGINT REFERENCES menu_categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Reservations Table
CREATE TABLE IF NOT EXISTS reservations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TIME NOT NULL,
  guests INTEGER NOT NULL,
  special_requests TEXT,
  special_code TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'pendiente' CHECK (status IN ('pendiente', 'completada', 'cancelada')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================================================
-- 2. SECURITY (ROW LEVEL SECURITY)
-- =============================================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;

-- Public Access to Menu
CREATE POLICY "Menu categories are public" ON menu_categories FOR SELECT USING (true);
CREATE POLICY "Menu items are public" ON menu_items FOR SELECT USING (true);

-- Private Access to Profiles and Reservations
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can view own reservations" ON reservations FOR SELECT USING (auth.uid() = user_id);

-- =============================================================================
-- 3. DATA SEEDING (MENU)
-- =============================================================================

-- Clean existing data to avoid duplicates
TRUNCATE TABLE menu_items CASCADE;
TRUNCATE TABLE menu_categories CASCADE;

-- Insert Categories
INSERT INTO menu_categories (name) VALUES
('japones'), ('chino'), ('sudeste'), ('infantil'), ('bebidas');

-- Insert Items using subqueries for safe category matching
INSERT INTO menu_items (category_id, name, price, description, image_url) VALUES
-- Japón
((SELECT id FROM menu_categories WHERE name='japones'), 'Omakase Premium', '$120', 'Selección del Chef: 12 piezas de sushi y sashimi de la temporada.', 'https://images.unsplash.com/photo-1579871494447-1c2818f4d46f?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='japones'), 'Ramen Tonkotsu', '$22', 'Caldo cremoso de cerdo cocinado por 18h, chashu y huevo marinado.', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='japones'), 'Tempura Imperial', '$18', 'Langostinos y vegetales rebozados en masa ligera y crujiente.', 'https://images.unsplash.com/photo-1581184720182-7b2937757796?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='japones'), 'Sashimi Deluxe', '$35', 'Cortes finos de atún, salmón y pulpo con wasabi fresco.', 'https://images.unsplash.com/photo-1534422477776-7500dcaec867?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='japones'), 'Yakitori Mix', '$20', 'Brochetas de pollo y vegetales asadas al carbón japonés.', 'https://images.unsplash.com/photo-1534422477776-7500dcaec867?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='japones'), 'Unagi Don', '$32', 'Anguila glaseada sobre una cama de arroz premium.', 'https://images.unsplash.com/photo-1581184720182-7b2937757796?q=80&w=600&auto=format&fit=crop'),

-- China
((SELECT id FROM menu_categories WHERE name='chino'), 'Pato Pekín', '$45', 'El clásico imperial con crepas, cebollino y salsa hoisin.', 'https://images.unsplash.com/photo-1585032226651-759ba4cb3674?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='chino'), 'Dim Sum Platter', '$24', 'Variedad de dumplings al vapor, bollos y gyozas.', 'https://images.unsplash.com/photo-1496116218417-1a782f7772ca?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='chino'), 'Mapo Tofu', '$20', 'Tofu picante estilo Szechuan con carne molida y pimienta.', 'https://images.unsplash.com/photo-1541696497730-7c8be7f64736?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='chino'), 'Pollo Kung Pao', '$22', 'Pollo salteado con cacahuates, chiles secos y pimientos.', 'https://images.unsplash.com/photo-1525755662778-98979d97383a?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='chino'), 'Sopa Agripicante', '$14', 'Sopa tradicional con tofu, hongos y brotes de bambú.', 'https://images.unsplash.com/photo-1547592166-2ud8ebc678b?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='chino'), 'Arroz Chaufa Imperial', '$18', 'Arroz salteado al wok con carnes seleccionadas y huevo.', 'https://images.unsplash.com/photo-1512058560366-c8065675966d?q=80&w=600&auto=format&fit=crop'),

-- Sudeste
((SELECT id FROM menu_categories WHERE name='sudeste'), 'Pad Thai Real', '$22', 'Fideos de arroz con camarones, tofu, cacahuates y lima.', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='sudeste'), 'Sopa Tom Yum', '$16', 'Sopa tailandesa picante y cítrica con camarones y lemongrass.', 'https://images.unsplash.com/photo-1548946767-aC577772c1fC?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='sudeste'), 'Bibimbap Coreano', '$24', 'Arroz mezclado con vegetales, carne, huevo y gochujang.', 'https://images.unsplash.com/photo-1590301157890-481760674682?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='sudeste'), 'Satay de Pollo', '$18', 'Brochetas tailandesas con salsa de cacahuate.', 'https://images.unsplash.com/photo-1562607395-726877723452?q=80&w=600&auto=format&fit=crop'),

-- Infantil
((SELECT id FROM menu_categories WHERE name='infantil'), 'Mini Sushi Kit', '$12', 'Piezas pequeñas de sushi seleccionadas para niños.', 'https://images.unsplash.com/photo-1579584425555-c35ca36B42c3?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='infantil'), 'Arroz con Pollo Dulce', '$10', 'Arroz suave con trozos de pollo en salsa agridulce.', 'https://images.unsplash.com/photo-1512058560366-c8065675966d?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='infantil'), 'Rollito Primavera Kids', '$8', 'Rollitos crujientes con vegetales suaves.', 'https://images.unsplash.com/photo-1541696497730-7c8be7f64736?q=80&w=600&auto=format&fit=crop'),

-- Bebidas
((SELECT id FROM menu_categories WHERE name='bebidas'), 'Té Matcha Imperial', '$8', 'Té verde ceremonial japonés batido a mano.', 'https://images.unsplash.com/photo-1582793988951-9a7557675d7a?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='bebidas'), 'Sake Premium', '$15', 'Sake filtrado en frío, notas cítricas y suaves.', 'https://images.unsplash.com/photo-1597303263268-736968d998e0?q=80&w=600&auto=format&fit=crop'),
((SELECT id FROM menu_categories WHERE name='bebidas'), 'Vino Riesling', '$18', 'Blanco alemán, el maridaje perfecto para el picante.', 'https://images.unsplash.com/photo-1510812431234?q=80&w=600&auto=format&fit=crop');
